name: App_Musei
description: "App per acquistare biglietti per musei."
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  logging: ^1.1.0
  material_design_icons_flutter: ^6.0.7096
  qr_flutter: ^4.0.0
  url_launcher: ^6.1.10  # Add this line

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
